apiVersion: v1
kind: ConfigMap
metadata:
  name: kibana-config
data:
  kibana.yml: |
    ---
    xpack.security.enabled: "false"
    #elasticsearch.username: "kibana"
    #elasticsearch.password: ""
    server.name: kibana
    server.host: '0'
    elasticsearch.url: http://elasticsearch:9200
    elasticsearch.requestTimeout: 120000
