---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  selector:
    component: kibana
  ports:
  - name: http
    port: 443
    targetPort: http
  #externalIPs:
  #- 10.x.x.x
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kibana
  labels:
    component: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana
  template:
    metadata:
      labels:
        component: kibana
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - {key: es-kibana, operator: In, values: ["true"]}
      containers:
      - name: kibana
        image: kp-kibana:6.3.2
        env:
        - name: CLUSTER_NAME
          value: analytics.valleychamp.com
        - name: PATH_DATA
          value: "/tmp"
        resources:
          limits:
            cpu: 4
          requests:
            cpu: 1
        ports:
        - containerPort: 5601
          name: http
        volumeMounts:
          - name: config
            mountPath: /usr/share/kibana/config
            readOnly: true
      volumes:
        - name: config
          configMap:
            name: kibana-config
